services:
  web:
    build: .
    container_name: mini-devops-web
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    profiles: ["dev","uat","prod"]

  nginx:
    image: nginx:alpine
    container_name: mini-devops-nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    profiles: ["dev", "uat", "prod"]
